/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.becomegood.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import cn.becomegood.struts.form.HelloForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-29-2016
 * 
 * XDoclet definition:
 * @struts.action path="/hello" name="helloForm" input="/form/hello.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/form/helloSuccess.jsp"
 */
public class HelloAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HelloForm helloForm = (HelloForm) form;// TODO Auto-generated method stub
		
		if (helloForm.getName()==null||helloForm.getName().trim().length()==0||
				helloForm.getPasswd()==null||helloForm.getPasswd().length()==0) {
			return mapping.getInputForward();
		}
		return mapping.findForward("success");
		

		
	}
}